services:
  # データベース
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fitbit_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # Goアプリ
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fitbiter_app
    restart: always
    depends_on:
      - db
    ports:
      - "9000:8080"
    env_file:
      - .env
    environment:
      - DB_DSN=host=db user=user password=password dbname=fitbit_db port=5432 sslmode=disable

  frontend:
    build:
      context: ./frontend
      target: dev # 開発時はDockerfile内のdevステージを使用
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app             # コードの変更を反映させる
      - /app/node_modules           # ★重要: node_modulesをホストに書き出さない
    environment:
      - VITE_API_BASE_URL=http://localhost:9000
    depends_on:
      - backend
