services:
  # データベース
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fitbit_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # Goアプリ
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fitbiter_app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_DSN=host=db user=user password=password dbname=fitbit_db port=5432 sslmode=disable
